warning('off', 'optim:fminunc:SwitchingMethod');
warning('off', 'MATLAB:singularMatrix');

iterations = 100;
variances = 0:0.000001:0.000025; % 0.005^2 = 0.000025
images = 1:30;
useSamePoints = true;

saveDirectories = char('out/sp_lsv/', ...
                       'out/sp_lsn/', ...
                       'out/sp_vt/', ...
                       'out/sp_sm/', ...
                       'out/sp_sc/');
methods = char('least squares valstar', ...
               'least squares new', ...
               'valstar test', ...
               'statistical mixed', ...
               'statistical complete');

test_variance('iterations', iterations, ...
              'values', variances, ...
              'saveDirectories', saveDirectories, ...
              'methods', methods, ...
              'useSamePoints', useSamePoints);

test_images('iterations', iterations, ...
            'values', images, ...
            'saveDirectories', saveDirectories, ...
            'methods', methods, ...
            'useSamePoints', useSamePoints);