function [ filename ] = method2Filename( method )

methods = {'least squares valstar', ...
           'least squares new', ...
           'statistical mixed', ...
           'valstar test', ...
           'statistical complete'};
filenames = {'_lsv', ...
             '_lsn', ...
             '_sm', ...
             '_vt', ...
             '_sc'};
methodMap = containers.Map(methods, filenames);
filename = methodMap(method);

end

